# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  push:
   tags:
    - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:


permissions:
  id-token: write  # allows GitHub Actions to generate OIDC tokens used for trusted publishing
  contents: write # required to write GH-release

jobs:
  
  release:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎
        uses: actions/checkout@v6

      - name: Install pnpm 👷🏽‍♂️
        uses: pnpm/action-setup@v6
        id: pnpm-install
        with:
          version: 11
          run_install: false
      
      - name: Setup node 👷🏽‍♂️
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
        
      - name: Install dependencies 👨🏻‍💻
        run: pnpm install
        
      - name: Run tests 🧪
        run: pnpm test

      - name: Build files 🔨
        run: pnpm build
        
      - name: Add release to Github 💾 
        uses: utomic-media/release-action@main
        with:
          artifacts: "dist/app.js,dist/api.js,package.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true

      # Ensure npm 11.5.1 or later is installed
      # Required, as we use node 22.x, which still comes with 10.X but trusted publishing using OICD requires npm >v11.5.1
      - name: Update npm 🐻
        run: npm install -g npm@latest

      - name: Add release to npm 💾 
        run: pnpm publish --no-git-checks # --no-git-checks as we're not on a branch but a tag!
